const Router = require('express')
const router= new Router ()
//const deviceRouter=require('./deviceRouter')
const userRouter=require('./userRouter')
//const brandRouter=require('./brandRouter')
//const typeRouter=require('./typeRouter')
const questionRouter=require('./questionRouter')
const answerRouter=require('./answerRouter')
const resultRouter=require('./resultRouter')
const fileRouter=require('./fileRouter')
const formulaRouter=require('./formulaRouter')

router.use('/user', userRouter)
//router.use('/type', typeRouter)
//router.use('/brand',brandRouter)
//router.use('/device',deviceRouter)
router.use('/test',questionRouter)
router.use('/file',fileRouter)
router.use('/formula',formulaRouter)
router.use('/answer',answerRouter)
router.use('/result',resultRouter)
module.exports=router