export const CABINET_ROUTE='/cabinet'
export const LOGIN_ROUTE='/login'
export const REGISTRATION_ROUTE='/registration'
export const START_ROUTE='/start'
export const TEST_ROUTE='/test'
export const EXCERCISE_ROUTE='/excercise'
export const LECTURE_ROUTE = '/lecture'